### PR TITLE
3 avoid todo item trimming

### LINKED ISSUE #3: Avoid overflow hidden for todo item
image
image

### PR DESCRIPTION
**Pull request by catalinmiron**
Fixes #3 

@Kemcake please review. I know that's not a big PR but I don't like the fact that when adding a todo item which have more than 1 line, the text is trimmed. So the output of this PR is the following:

image

### CODE REVIEW

**Comment by catalinmiron** [comment]
@Kemcake please review

**Comment by remstos** [comment]
You're right, good idea :+1:

**Comment by remstos** [comment]
Thanks :open_hands:

**Comment by catalinmiron** [comment]
@Kemcake no problem. Right now I'm working on adding separate files for each component, since we're usign webpack for the build, we can import the styles in each component. wdyt?

**Pull request merged**
