### PR TITLE
Enhance project

### PR DESCRIPTION
**Pull request by catalinmiron**
- Webpack
- Babel
- [React transform boilerplate](https://github.com/gaearon/react-transform-boilerplate)
  - Hot reloading
  - Error catching
- [Parse React](https://github.com/ParsePlatform/ParseReact)
- ~~Sass or~~ Less for now.
- [Eslint](http://eslint.org/)
- ~~Unit testing (right now nothing but it will be the following)~~ as soon as possible
- ~~Visual testing~~ as soon as possible
- [React Router](https://github.com/rackt/react-router)

### CODE REVIEW

**Comment by catalinmiron** [comment]
This is just the code that I have on my laptop right now, is not the final version. Improvements are coming.
- [x] ES6
- [ ] Unit testing
- [ ] Visual testing

**Comment by catalinmiron** [comment]
@Kemcake I added ES6 support. Can you take a look?

**Comment by remstos** [comment]
Wow, that's awesome! Really nice stack, and I definitely love ES6 syntax.
Just a minor comment:  you use `export default class XXX` (when there's no defaultProps I guess), but I find it way more consistent to always export at the bottom of the file. What's your thoughts on this?

What else do you want to add before merge?

**Comment by catalinmiron** [comment]
Thanks @Kemcake :) Yes, I think that adding `export default XXX` at the bottom of the component is a good practice. I'll modify it right now. 

I'm playing with `TodoDetails`, I'm addind a `description` saved as `markdown`, I'm just playing with it :+1: 

Adding unit tests is a _MUST HAVE_ and it will be a new issue which I'll create.

**Comment by remstos** [comment]
Alright, once you updated that `export` thing (and also finished playing with the description ;)) I'll be happy to merge!

**Comment by catalinmiron** [comment]
@Kemcake we're good to go.

**Comment by remstos** [comment]
Thanks @catalinmiron. A fresh new starter project :+1: !

**Comment by catalinmiron** [comment]
``` javascript
componentWillMount() {
  if (this.props.isFun && this.props.isOpenSource) {
    return "my pleasure";
  }
}
```

**Pull request merged**
